
desc 'ManagerLib 使用这个航道, 可以快速的对自己的私有库, 进行升级维护'
lane :ManagerLib do |options|

tagName = options[:tag]
targetName = options[:target]
commitDesc = options[:desc]

# 使用示例
# fastlane ManagerLib tag:0.1.0 target:targetName desc:版本更新
UI.message("fastlane ManagerLib tag:0.1.0 target:targetName desc:版本更新  请检查参数传递是否正确 🚀")


# 具体这个巷道上面执行哪些行为

# 1. pod install
cocoapods(
clean: true,
podfile: "./Example/Podfile"
)

# 2. git add .
git_add(path: ".")
#    git commit -m 'xxx'

if commitDesc == nil
	git_commit(path: ".", message: "默认提交日志,xxx")
else
	git_commit(path: ".", message: "#{commitDesc}")
end

# git_commit(path: ".", message: "#{commitDesc}")
#    git push origin master
push_to_git_remote

# 验证tag是否存在,如果存在, 应该删除本地标签和远程标签
#if 判断标签是否存在
#    执行删除本地/远程标签
#end

if git_tag_exists(tag: tagName)
    UI.message("发现tag:#{tagName} 已经存在, 即将执行, 删除动作 🚀")
    remove_tag(tag:tagName)
end


# 3. git tag 标签名称
add_git_tag(
tag: tagName
)
#    git push --tags
push_git_tags

# 4. pod spec lint
# pod_lib_lint(allow_warnings: true)
#    pod repo push XXXX xxx.podspec
pod_push(path: "#{targetName}.podspec", repo: "master", sources: ["https://github.com/CocoaPods/Specs"], allow_warnings: true)


end
